name: 'po_quality'
version: '1.0.0'
config-version: 2

profile: 'po_quality'

model-paths: ["models"]
test-paths: ["tests"]
macro-paths: ["macros"]

clean-targets: ["target", "dbt_packages"]

models:
  po_quality:
    staging:
      +materialized: view
      +schema: STAGING
    quarantine:
      +materialized: table
      +schema: QUARANTINE
    silver:
      +materialized: table
      +schema: SILVER
    gold:
      +materialized: table
      +schema: GOLD
    evaluation:
      +materialized: table
      +schema: EVALUATION
    monitoring:
      +materialized: view
      +schema: MONITORING

data_tests:
  +severity: warn
  +store_failures: true
  +schema: TEST_FAILURES